### ISSUE TITLE
unable to read prefix from socket: No error information

### ISSUE THREAD

**Issue by imlinfly** [roadrunner-server/goridge#185]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Hello,
I'm having a problem with goridge-php, I'm getting an error when I run the demo code you gave, this is the exception thrown by PHP:
```
PHP Fatal error:  Uncaught Spiral\Goridge\Exceptions\PrefixException: unable to read prefix from socket: No error information in /project/GoAndPhp/goridge/vendor/spiral/goridge/src/SocketRelay.php:305
Stack trace:
#0 /project/GoAndPhp/goridge/vendor/spiral/goridge/src/SocketRelay.php(184): Spiral\Goridge\SocketRelay->fetchPrefix()
#1 /project/GoAndPhp/goridge/vendor/spiral/goridge/src/RPC.php(82): Spiral\Goridge\SocketRelay->receiveSync()
#2 /project/GoAndPhp/goridge/run.php(20): Spiral\Goridge\RPC->call()
#3 {main}
  thrown in /project/GoAndPhp/goridge/vendor/spiral/goridge/src/SocketRelay.php on line 305
```

Golang log is as follows:
```
2023/01/06 14:40:37 rpc: rpc: server cannot decode request: goridge_frame_receive: validation failed on the message sent to STDOUT, see: https://roadrunner.dev/docs/known-issues-stdout-crc/2.x/en, invalid message: App.Hi"Hello"
```

PHP Code:
```php
<?php

declare (strict_types=1);

use Spiral\Goridge\Relay;
use Spiral\Goridge\RPC;

require_once __DIR__ . '/vendor/autoload.php';

$rpc = new RPC(
    Relay::create('tcp://127.0.0.1:6001')
);

var_dump($rpc->call('App.Hi', 'Hello'));
```

Golang code:
```go
package main

import (
	"fmt"
	"net"
	"net/rpc"

	goridgeRpc "github.com/roadrunner-server/goridge/v3/pkg/rpc"
)

type App struct{}

func (s *App) Hi(name string, r *string) error {
	*r = fmt.Sprintf("Hello, %s!", name)
	return nil
}

func main() {
	ln, err := net.Listen("tcp", ":6001")
	if err != nil {
		panic(err)
	}

	_ = rpc.Register(new(App))

	fmt.Println("RPC server started on :6001")

	for {
		conn, err := ln.Accept()
		if err != nil {
			continue
		}
		_ = conn

		fmt.Printf("New connection from %s\n", conn.RemoteAddr().String())

		go rpc.ServeCodec(goridgeRpc.NewCodec(conn))
	}
}
```

### Version

goridge  v3.6.2
goridge-php v3.2.0
php 8.0
golang 1.19

**Comment by rustatian** [comment]
Hey @imlinfly 👋🏻 
I double checked your case, but it seems that somewhere in your app you're pushing this message (or log) `App.Hi"Hello"` to the stdout instead of stderr. Stdout is designed for the communication between processed, while `stderr` for the logs and diagnostic info.

I've added an additional test here: https://github.com/roadrunner-server/goridge/blob/master/test/issues/issue_185_test.go
